language: node_js
node_js:
  - 12
jobs:
  include:
    - state: download doc
      if: type = cron
      script: npm run sync:all
      after_success: bash ./tools/syncAndMerge.sh
    - state: lint
      script: npm run lint
    - stage: deploy to staging
      if: branch = master
      script: npm run generate:staging
      deploy:
        provider: pages:git
        edge: true # opt in to dpl v2
        github_token: $GITHUB_TOKEN
        local_dir: dist
    - stage: deploy to production
      if: tag =~ /^release-/
      script: npm run generate:production
      deploy:
        provider: pages:git
        edge: true # opt in to dpl v2
        github_token: $GITHUB_TOKEN
        target_branch: production-pages
        local_dir: dist
        on:
          tags: true

