language: node_js
node_js:
  - 12
jobs:
  include:
    - state: lint
      script: npm run lint
    - stage: deploy to staging
      if: branch = master
      script: npm run generate:staging
      deploy:
        provider: pages:git
        edge: true # opt in to dpl v2
        github_token: $GITHUB_TOKEN
        local_dir: dist
    - stage: release to production
      if: (branch = master) AND (tag =~ ^release-)
      script: bash ./tools/release.sh
    - stage: deploy to production
      if: branch = production
      script: npm run generate:prod
      deploy:
        provider: pages:git
        edge: true # opt in to dpl v2
        github_token: $GITHUB_TOKEN
        target_branch: production-pages
        local_dir: dist

